### PR TITLE
Kp/solar system extended

### PR DESCRIPTION
**Pull request by kyra-at-ada**
Summary of Changes:
- Add query params `sort` and `name` to Wave 5  activity instructions (More Queries)
- Add additional required tests to Wave 6 activity instructions (Testing)
- Add requirement to brainstorm and implement three additional tests to Wave 6 activity instructions (Testing)
- Add Solar System API Wave 7 Activity - mirror refactors done with Hello Books API (Refactoring)
- Add Solar System Wave 8 Activity - Create Moons model and associated Create/Read routes (One-to-Many)
- Modify Wave 9 activity instructions to make deploying Solar System API a more explicit requirement (deployment)

### CODE REVIEW

**Review by ilana-adadev — APPROVED** [review]
Looks good to me :)

**Review by ilana-adadev — APPROVED** [review]
I like the additional clarity and the addition of the task list checkboxes.

**Comment by ilana-adadev** [comment]
I have some additional comments after reviewing this on the AC2 Accelerate Sandbox on Learn:



1. https://learn-2.galvanize.com/cohorts/3586/blocks/1310/content_files/intro-to-api-design/activity-intro-to-api-design.md
"Solar System" doesn't appear as the title and so, it's not listed in the TOC, in case anyone's looking for it

2. https://learn-2.galvanize.com/cohorts/3586/blocks/1310/content_files/api-8-relationships-in-sqlalchemy/activity-solar-moons.md
 ^ This is called Wave 7. Should this be wave 8? This was already called Wave 7: https://learn-2.galvanize.com/cohorts/3586/blocks/1310/content_files/api-7-refactoring/activity-solar-refactoring.md

**Comment by kyra-at-ada** [comment]
> I have some additional comments after reviewing this on the AC2 Accelerate Sandbox on Learn:
> 
>     1. https://learn-2.galvanize.com/cohorts/3586/blocks/1310/content_files/intro-to-api-design/activity-intro-to-api-design.md
>        "Solar System" doesn't appear as the title and so, it's not listed in the TOC, in case anyone's looking for it
> 
>     2. https://learn-2.galvanize.com/cohorts/3586/blocks/1310/content_files/api-8-relationships-in-sqlalchemy/activity-solar-moons.md
>        ^ This is called Wave 7. Should this be wave 8? This was already called Wave 7: https://learn-2.galvanize.com/cohorts/3586/blocks/1310/content_files/api-7-refactoring/activity-solar-refactoring.md

**Pull request merged**
